# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: proba

on:
  [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Bahur
      run: |
        echo $USER
        echo ${GITHUB_SHA::8}
        echo RUN_ID=${{ github.event.workflow_run.id }}
